apiVersion: extensions/v1beta1
kind: Pod
metadata:
   name: devops-pod-stable
   namespace: devops
spec:
  rules:
  - host: devopsstage.example.com
    http:
	  paths:
	  - path: /
	    backend:
		   serviceName: devops-svc-stable
		   servicePort: 80
