apiVersion: v1
kind: Service
metadata:
   name: devops-svc-stable
   namespace: devops
spec:
  ports:
  - port: 80
    targetPort: 80
	protocol: TCP
	name: http
  selector:
     app: devops
	 version: green
  type: LoadBalancer